version: '2'

services:
  geotrellis:
    image: gtserver
    build:
      context: ./geotrellis
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    volumes:
      - "/home/colin/.ivy2:/root/.ivy2"
      - "/home/colin/.m2:/root/.m2"
      - "/home/colin/.sbt:/root/.sbt"
  jekyll:
    image: jekyll-nginx
    build:
      context: ./jekyll
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
